// <auto-generated />
using System;
using GelirGiderTakip.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GelirGiderTakip.Api.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260908193019_IlkVeritabaniOlusumu")]
    partial class IlkVeritabaniOlusumu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GelirGiderTakip.Api.Models.Bildirim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ButceId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("OkunmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Tur")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ButceId");

                    b.HasIndex("KullaniciId", "OkunmaTarihi", "OlusturulmaTarihi");

                    b.ToTable("Bildirimler", null, t =>
                        {
                            t.HasCheckConstraint("CK_Bildirimler_Tur", "[Tur] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("GelirGiderTakip.Api.Models.Butce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Ay")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<decimal>("LimitTutari")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<short>("Yil")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("KullaniciId", "Yil", "Ay")
                        .IsUnique()
                        .HasFilter("[KategoriId] IS NULL");

                    b.HasIndex("KullaniciId", "KategoriId", "Yil", "Ay")
                        .IsUnique()
                        .HasFilter("[KategoriId] IS NOT NULL");

                    b.ToTable("Butceler", null, t =>
                        {
                            t.HasCheckConstraint("CK_Butceler_Ay", "[Ay] BETWEEN 1 AND 12");

                            t.HasCheckConstraint("CK_Butceler_LimitTutari", "[LimitTutari] > 0");

                            t.HasCheckConstraint("CK_Butceler_Yil", "[Yil] BETWEEN 2000 AND 2100");
                        });
                });

            modelBuilder.Entity("GelirGiderTakip.Api.Models.FinansalIslem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("FisId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsletmeId")
                        .HasColumnType("int");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Tur")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FisId")
                        .IsUnique()
                        .HasFilter("[FisId] IS NOT NULL");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("KategoriId");

                    b.HasIndex("KullaniciId", "IslemTarihi");

                    b.ToTable("FinansalIslemler", null, t =>
                        {
                            t.HasCheckConstraint("CK_FinansalIslemler_Tur", "[Tur] IN (1, 2)");

                            t.HasCheckConstraint("CK_FinansalIslemler_Tutar", "[Tutar] > 0");
                        });
                });

            modelBuilder.Entity("GelirGiderTakip.Api.Models.Fis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlgilananIsletmeAdi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("AlgilananTarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("AlgilananTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("Durum")
                        .HasColumnType("tinyint");

                    b.Property<string>("HamOcrMetni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HataMesaji")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("IslenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("OrijinalDosyaAdi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("YuklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId", "YuklenmeTarihi");

                    b.ToTable("Fisler", (string)null);
                });

            modelBuilder.Entity("GelirGiderTakip.Api.Models.FisDetayi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BirimFiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FisId")
                        .HasColumnType("int");

                    b.Property<string>("HamSatirMetni")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Miktar")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int");

                    b.Property<decimal>("ToplamTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("FisId", "SiraNo")
                        .IsUnique();

                    b.ToTable("FisDetaylari", (string)null);
                });

            modelBuilder.Entity("GelirGiderTakip.Api.Models.Isletme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique()
                        .HasFilter("[OlusturanKullaniciId] IS NULL");

                    b.HasIndex("OlusturanKullaniciId", "Ad")
                        .IsUnique()
                        .HasFilter("[OlusturanKullaniciId] IS NOT NULL");

                    b.ToTable("Isletmeler", (string)null);
                });

            modelBuilder.Entity("GelirGiderTakip.Api.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Tur")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("Ad", "Tur")
                        .IsUnique()
                        .HasFilter("[KullaniciId] IS NULL");

                    b.HasIndex("KullaniciId", "Ad", "Tur")
                        .IsUnique()
                        .HasFilter("[KullaniciId] IS NOT NULL");

                    b.ToTable("Kategoriler", (string)null);
                });

            modelBuilder.Entity("GelirGiderTakip.Api.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParolaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Eposta")
                        .IsUnique();

                    b.ToTable("Kullanicilar", (string)null);
                });

            modelBuilder.Entity("GelirGiderTakip.Api.Models.Bildirim", b =>
                {
                    b.HasOne("GelirGiderTakip.Api.Models.Butce", "Butce")
                        .WithMany("Bildirimler")
                        .HasForeignKey("ButceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GelirGiderTakip.Api.Models.Kullanici", "Kullanici")
                        .WithMany("Bildirimler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Butce");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("GelirGiderTakip.Api.Models.Butce", b =>
                {
                    b.HasOne("GelirGiderTakip.Api.Models.Kategori", "Kategori")
                        .WithMany("Butceler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GelirGiderTakip.Api.Models.Kullanici", "Kullanici")
                        .WithMany("Butceler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("GelirGiderTakip.Api.Models.FinansalIslem", b =>
                {
                    b.HasOne("GelirGiderTakip.Api.Models.Fis", "Fis")
                        .WithOne("FinansalIslem")
                        .HasForeignKey("GelirGiderTakip.Api.Models.FinansalIslem", "FisId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GelirGiderTakip.Api.Models.Isletme", "Isletme")
                        .WithMany("FinansalIslemler")
                        .HasForeignKey("IsletmeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GelirGiderTakip.Api.Models.Kategori", "Kategori")
                        .WithMany("FinansalIslemler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GelirGiderTakip.Api.Models.Kullanici", "Kullanici")
                        .WithMany("FinansalIslemler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fis");

                    b.Navigation("Isletme");

                    b.Navigation("Kategori");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("GelirGiderTakip.Api.Models.Fis", b =>
                {
                    b.HasOne("GelirGiderTakip.Api.Models.Kullanici", "Kullanici")
                        .WithMany("Fisler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("GelirGiderTakip.Api.Models.FisDetayi", b =>
                {
                    b.HasOne("GelirGiderTakip.Api.Models.Fis", "Fis")
                        .WithMany("FisDetaylari")
                        .HasForeignKey("FisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GelirGiderTakip.Api.Models.Kategori", "Kategori")
                        .WithMany("FisDetaylari")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Fis");

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("GelirGiderTakip.Api.Models.Isletme", b =>
                {
                    b.HasOne("GelirGiderTakip.Api.Models.Kullanici", "OlusturanKullanici")
                        .WithMany("OlusturduguIsletmeler")
                        .HasForeignKey("OlusturanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OlusturanKullanici");
                });

            modelBuilder.Entity("GelirGiderTakip.Api.Models.Kategori", b =>
                {
                    b.HasOne("GelirGiderTakip.Api.Models.Kullanici", "Kullanici")
                        .WithMany("Kategoriler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("GelirGiderTakip.Api.Models.Butce", b =>
                {
                    b.Navigation("Bildirimler");
                });

            modelBuilder.Entity("GelirGiderTakip.Api.Models.Fis", b =>
                {
                    b.Navigation("FinansalIslem");

                    b.Navigation("FisDetaylari");
                });

            modelBuilder.Entity("GelirGiderTakip.Api.Models.Isletme", b =>
                {
                    b.Navigation("FinansalIslemler");
                });

            modelBuilder.Entity("GelirGiderTakip.Api.Models.Kategori", b =>
                {
                    b.Navigation("Butceler");

                    b.Navigation("FinansalIslemler");

                    b.Navigation("FisDetaylari");
                });

            modelBuilder.Entity("GelirGiderTakip.Api.Models.Kullanici", b =>
                {
                    b.Navigation("Bildirimler");

                    b.Navigation("Butceler");

                    b.Navigation("FinansalIslemler");

                    b.Navigation("Fisler");

                    b.Navigation("Kategoriler");

                    b.Navigation("OlusturduguIsletmeler");
                });
#pragma warning restore 612, 618
        }
    }
}
